name: 'Push NuGet Package'
description: 'Push NuGet Package'

inputs:
  artifact:
    description: "Artifact Name"
    required: true
  nuget-api-url:
    description: "NuGet URL"
    default: 'https://api.nuget.org/v3/index.json'
  nuget-api-key:
    description: 'NuGet API key'
    required: true
  optional-arguments:
    description: 'Optional arguments'
    default: '--skip-duplicate'
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Push packages
      shell: bash
      run: find ** -type f -regex '.*\.s?nupkg' -exec dotnet nuget push -k ${{ inputs.nuget-api-key }} -s "${{ inputs.nuget-api-url }}" ${{ inputs.optional-arguments }} {} \;